<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_create_another</name>
   <tag></tag>
   <elementGuidId>f38f5041-bc3c-43ca-9295-c7db2df0cbd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category_return_to_form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='category_return_to_form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2aae9e1-d7e3-4bd1-bd5e-c3afdef95f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>561b31ca-6407-4451-824a-c1a81307687e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>create_another</value>
      <webElementGuid>f406fe3b-0c47-416a-92c6-a258bb4a1d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category_return_to_form</value>
      <webElementGuid>ba2efe72-67b4-48a1-89d9-4a8d1a35c132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c4d0551c-cdfa-43a3-a7cb-92caa901863f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_return_to_form&quot;)</value>
      <webElementGuid>6dde65e1-3dda-4e06-8e44-930d9c5abac1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='category_return_to_form']</value>
      <webElementGuid>f26af1c1-74cc-43c4-874f-e3a80194a797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='store']/div[2]/div/div/div[2]/div/div/div/label/input</value>
      <webElementGuid>c3d1beaa-f9e0-4c2d-91a5-c270d24bf2e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>80e70f7e-c4b6-4b98-86c5-fc58eadef60f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'create_another' and @id = 'category_return_to_form']</value>
      <webElementGuid>2fbfe23c-1028-431b-aa04-dc0ad130997f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
