<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_create_another</name>
   <tag></tag>
   <elementGuidId>f38f5041-bc3c-43ca-9295-c7db2df0cbd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#category_return_to_form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='category_return_to_form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>044493f2-2bc9-42e1-a285-69a008f78a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ffdb83d4-191b-46b1-9198-d98071ababff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>create_another</value>
      <webElementGuid>a289a0e3-da15-467b-aa28-568f78200712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>category_return_to_form</value>
      <webElementGuid>440ce085-28f7-43a9-abdf-77994382ac66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>239530b2-aa6a-468b-85e1-c9da7949e5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;category_return_to_form&quot;)</value>
      <webElementGuid>1190cc6a-29f8-4e16-ac49-292dd5a1163a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='category_return_to_form']</value>
      <webElementGuid>53ba8491-42ec-4687-8f86-b81a1e75c69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='store']/div[2]/div/div/div[2]/div/div/div/label/input</value>
      <webElementGuid>601d5d31-3eb0-487b-90fa-73a72fd2d895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>9c6cfb5f-e85b-44a7-8f4e-f784bb59bae9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'create_another' and @id = 'category_return_to_form']</value>
      <webElementGuid>c23b9450-6b5a-4d54-b75d-35fcb55ff363</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
