<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Create New Recurring Transaction</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>28ec6e35-90bf-45a0-9768-e531adaab090</testSuiteGuid>
   <testCaseLink>
      <guid>1664b3bc-965a-464e-a266-f0618e150e8e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/01_Tạo recurring transaction có tất cả các trường thông tin hợp lệ</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e22795e-7160-4da8-a191-814efb7ad052</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e863aaa2-fe53-460f-ac19-c972da27e0b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bdbf6bf-4137-4902-bf76-c0237aebc392</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94e4f549-c85f-4f30-81ef-cb1c3f9bfe6a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b5f1c974-fff5-4d92-80fe-090a41c2348d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/02_Tạo recurring transaction có tất cả các trường thông tin hợp lệ 2</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97cdf79d-a5ad-497d-8e4b-3b4c3958705a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3158ecb7-d488-437a-a02b-b6a195bff719</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41d45ed2-b86b-49ec-b143-32cec329ea93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1720c95-7be8-409e-8e4f-f7a5c3ba8009</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30c8ff8e-ac39-45c9-9136-f3eaed3eab3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>801148bd-684f-455b-8eaa-d7d45f39a3a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d66279f-9d68-49df-b37e-c27b655c4ccc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81431f45-6d37-4436-b7b0-76deb4b6d32a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a95f67a-ca21-4a5f-a8ea-264174dfe7f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e3f093a-1d8f-4d93-a2dc-f41d3e861db1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/03_Tạo recurring transaction có tất cả các trường thông tin hợp lệ 3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8028d2c-72dc-4cb2-93f4-5b859cea9c60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>439341e4-96a4-49e0-9dff-879c1ee4d799</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8631a1ad-70db-4c76-bb69-05d7246fe6d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f93fc23f-0a89-49c1-9755-4a0f3af553fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83f61f74-4646-4ed9-aceb-52fb2a1555a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>155a50a0-7402-43a1-aecc-9f958ef326b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e84fb9a8-f84d-4dc4-8f3c-eb96a3db9273</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/04_Tạo recurring transaction với Title không nhập, Skip âm, Recurring transaction description quá dài</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2f449a6-3b81-407b-b7cd-515113d66fd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e331c1f1-178c-4c47-925e-3a42d49e91e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a69ca980-7518-4604-b403-62c69bf647d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c91139f2-6539-48b5-b3e5-415b1382efcb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>feea6c9a-e5e2-4678-b89e-0e48e45483cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea1154a9-e732-4746-8524-e2d19256828b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3ef3c031-3a51-4604-a585-7211cd3cd34e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/05_Tạo recurring transaction với Title quá dài, Skip vượt khoảng, Transaction description quá dài</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b27478c6-8575-4d68-8cbe-85413f0d965b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87059892-f873-43e3-a04e-a0e4beee046e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1750233e-c924-4248-a605-767d7bc48431</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4ace7ef-2d59-4190-b0df-76db726f6307</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f61d70c8-5447-467e-9812-375783b5a893</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>af897cdb-b806-4341-9245-7cce393493ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/06_Tạo recurring transaction với Skip không hợp lệ, Repetition quá khoảng, Amount không hợp lệ</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>9c3a749e-60bb-41f4-87b2-b69026bbb50a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/07_Tạo recurring transaction với Repetition âm</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>6ddc2a8a-c63e-4c24-8472-7b66635284c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/08_Tạo recurring transaction với Repetition là số thập phân</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>04e551bf-94ba-45b7-8d75-828c37cc1463</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/09_Tạo recurring transaction với Repeat until trước ngày hôm nay</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>44e8904a-637a-453a-8ff9-55af4a3217c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/10_Tạo recurring transaction với Attachments lớn hơn 2MB</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
