<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Create new recurring transaction</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>24bf3506-8606-4c19-a12c-6ed7a6260cce</testSuiteGuid>
   <testCaseLink>
      <guid>eb6888a5-126e-491c-83d8-08caa1b70811</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/01_Tạo recurring transaction có tất cả các trường thông tin hợp lệ</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e22795e-7160-4da8-a191-814efb7ad052</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e863aaa2-fe53-460f-ac19-c972da27e0b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bdbf6bf-4137-4902-bf76-c0237aebc392</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94e4f549-c85f-4f30-81ef-cb1c3f9bfe6a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>05e378b7-b73a-48b8-9eaf-baa1ffab0192</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/02_Tạo recurring transaction có tất cả các trường thông tin hợp lệ 2</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97cdf79d-a5ad-497d-8e4b-3b4c3958705a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3158ecb7-d488-437a-a02b-b6a195bff719</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41d45ed2-b86b-49ec-b143-32cec329ea93</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1720c95-7be8-409e-8e4f-f7a5c3ba8009</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>30c8ff8e-ac39-45c9-9136-f3eaed3eab3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>801148bd-684f-455b-8eaa-d7d45f39a3a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d66279f-9d68-49df-b37e-c27b655c4ccc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81431f45-6d37-4436-b7b0-76deb4b6d32a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a95f67a-ca21-4a5f-a8ea-264174dfe7f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3de4be42-2c61-4e06-83d2-8773f8359896</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/03_Tạo recurring transaction có tất cả các trường thông tin hợp lệ 3</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b8028d2c-72dc-4cb2-93f4-5b859cea9c60</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>439341e4-96a4-49e0-9dff-879c1ee4d799</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8631a1ad-70db-4c76-bb69-05d7246fe6d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f93fc23f-0a89-49c1-9755-4a0f3af553fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83f61f74-4646-4ed9-aceb-52fb2a1555a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>155a50a0-7402-43a1-aecc-9f958ef326b2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8511f467-f17c-4812-b721-2b6eb025c946</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/04_Tạo recurring transaction với Title không nhập, Skip âm, Recurring transaction description quá dài</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2f449a6-3b81-407b-b7cd-515113d66fd5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e331c1f1-178c-4c47-925e-3a42d49e91e3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a69ca980-7518-4604-b403-62c69bf647d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c91139f2-6539-48b5-b3e5-415b1382efcb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>feea6c9a-e5e2-4678-b89e-0e48e45483cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea1154a9-e732-4746-8524-e2d19256828b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ce25ccb4-dec8-4010-8c10-abb4f9e086ef</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/05_Tạo recurring transaction với Title quá dài, Skip vượt khoảng, Transaction description quá dài</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b27478c6-8575-4d68-8cbe-85413f0d965b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>87059892-f873-43e3-a04e-a0e4beee046e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1750233e-c924-4248-a605-767d7bc48431</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4ace7ef-2d59-4190-b0df-76db726f6307</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f61d70c8-5447-467e-9812-375783b5a893</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f118f55d-526f-4dc2-b774-c6c8bc1b3a83</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/06_Tạo recurring transaction với Skip không hợp lệ, Repetition quá khoảng, Amount không hợp lệ</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>689aba3f-639a-4dbb-b794-e4002c9a458c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/07_Tạo recurring transaction với Repetition âm</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>9b418c36-facc-40cd-807b-1a1a3c3d6d6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/08_Tạo recurring transaction với Repetition là số thập phân</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>33b1b3c3-ba98-4391-b3e0-33adea09b8d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/09_Tạo recurring transaction với Repeat until trước ngày hôm nay</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>c6b9f3c9-5056-48d1-9d61-275ded382591</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create new recurring transaction/10_Tạo recurring transaction với Attachments lớn hơn 2MB</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
