<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Deposit</name>
   <tag></tag>
   <elementGuidId>fbff9726-1ca5-4958-a9dd-e03358dbcfaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-default.switch-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='name_holder']/div/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d4c12d07-3c64-40ac-8dbd-2bfb44030509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>01fcbb8d-fc4b-452e-9fe8-345ebaf8a6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default switch-button</value>
      <webElementGuid>981a88be-72ef-4575-a12e-8c534ead26d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>deposit</value>
      <webElementGuid>a6082baa-4c9b-45a6-b3af-6a0fa13ec422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Deposit</value>
      <webElementGuid>ceef9b43-e89b-4b5d-96bb-a9f631edb5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name_holder&quot;)/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;btn-group btn-group-sm&quot;]/a[@class=&quot;btn btn-default switch-button&quot;]</value>
      <webElementGuid>5f43fe76-a658-40a7-9e63-51e443e1d559</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='name_holder']/div/div/a[2]</value>
      <webElementGuid>a8918190-3bce-4ee0-bc45-0d8ea46d04c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Deposit')]</value>
      <webElementGuid>8bb7f293-9a98-4d2e-b6b0-b8794fd2e33d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[12]</value>
      <webElementGuid>b8a101bc-4f1f-4b8a-99db-14f48728c704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>8d691866-e1cc-49d6-b95c-6ed0e0e163fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Deposit' or . = 'Deposit')]</value>
      <webElementGuid>9b0503dc-25a5-46c8-b688-3c5113308f6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
