<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_col-sm-8</name>
   <tag></tag>
   <elementGuidId>3ca4f859-27e5-4bda-9277-b124ed41ffc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#skip_holder > div.col-sm-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='skip_holder']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4c9dafc2-0328-41a4-82b7-b9a5e4df27d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-sm-8</value>
      <webElementGuid>7fc20a5c-5a3b-46fb-acd1-817e8d3d8bac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skip_holder&quot;)/div[@class=&quot;col-sm-8&quot;]</value>
      <webElementGuid>9f96193f-b36b-4a66-abf5-1a22d85b8d3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='skip_holder']/div</value>
      <webElementGuid>2b343757-d73a-4cb6-be6a-ac960fcaf44d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div</value>
      <webElementGuid>b225d0c0-bcde-40eb-853e-2fa63219dc3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
