<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_amount</name>
   <tag></tag>
   <elementGuidId>db50255b-c3d0-4c7c-b7bf-f124b561b618</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_amount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ffInput_amount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ec4bd92-002f-495c-9c03-67ac1300e1ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ae41001b-23ed-423c-ba6d-1c449fe3f2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>41d38b93-9f08-4ee9-823b-cfaead2cf43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>amount</value>
      <webElementGuid>a9f6d21a-7b17-4a24-b7c0-e24c979e27b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_amount</value>
      <webElementGuid>a397e723-0b44-4330-b5b8-50b42e056b5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>d41e3f4b-9006-48aa-9254-009f4f713a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>280e089a-ae32-429c-a653-b8659d3a3d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d3713298-77e8-4ca1-a973-ce67974d41ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_amount&quot;)</value>
      <webElementGuid>cd5c34ec-1ae1-43da-b9fa-bf1441c8a0d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ffInput_amount']</value>
      <webElementGuid>83bed7af-1fbc-4d16-b5a7-9b1683272c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='amount_holder']/div/input</value>
      <webElementGuid>d1205be4-9ae8-4baf-a6fa-e4a7aadf5a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[4]/div/input</value>
      <webElementGuid>0c9b5a0b-e75e-48fc-bc0d-cb2448a9181f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'amount' and @id = 'ffInput_amount']</value>
      <webElementGuid>ba396680-3a01-49c3-928c-bc798f5d116c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
