<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_create_another</name>
   <tag></tag>
   <elementGuidId>0c2c2546-a7a2-4ebf-affc-1d741f92b113</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#recurrence_return_to_form</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='recurrence_return_to_form']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3dbfd923-4a42-45e8-b563-df3586ef1a12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ae11b4b5-f5dd-46fd-b9e0-2e3cb3ee3551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>create_another</value>
      <webElementGuid>d6ca3b09-4106-4ccf-b65f-6f034183f216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recurrence_return_to_form</value>
      <webElementGuid>12212f8b-527a-40dd-90ab-44c31739aac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6c5518db-65be-446c-8fc7-8f984a4b7a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recurrence_return_to_form&quot;)</value>
      <webElementGuid>ba4d814f-3ea6-404b-a0c3-3d4880228a67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='recurrence_return_to_form']</value>
      <webElementGuid>460d9390-4804-48cf-8262-6ed6352e2e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='store']/div[3]/div/div/div[2]/div/div/div/label/input</value>
      <webElementGuid>d9e852c2-a06b-4f77-8733-19fbd005fdfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/label/input</value>
      <webElementGuid>cbdcf3e7-85fd-4542-b9de-23091321aeea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'create_another' and @id = 'recurrence_return_to_form']</value>
      <webElementGuid>7b2ff278-9849-438c-9045-841b8f459781</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
