<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_apply_rules</name>
   <tag></tag>
   <elementGuidId>66216f75-e949-4214-9ac7-4762875ece36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_apply_rules</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ffInput_apply_rules']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ca01f91d-86a4-494f-81aa-9da788af3921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f68fafb8-7a82-4c00-9966-4f6a6d9c4577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>apply_rules</value>
      <webElementGuid>f10c31cb-dfa3-409e-b402-c865f8a166e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_apply_rules</value>
      <webElementGuid>8c780478-45f6-46d2-a130-6bfc882b05ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>456201ab-f8a3-484a-b828-bbb45da5c391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_apply_rules&quot;)</value>
      <webElementGuid>b37b253a-9f40-4ffe-a08a-1b275aabeda6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ffInput_apply_rules']</value>
      <webElementGuid>403f78bb-3931-4323-af38-1870a4e608e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='apply_rules_holder']/div/div/label/input</value>
      <webElementGuid>e852620c-048a-486a-bc71-c3e2d7d1df67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/label/input</value>
      <webElementGuid>61a01008-0256-4761-bd11-f543a8224a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'apply_rules' and @id = 'ffInput_apply_rules']</value>
      <webElementGuid>42b59422-a7c0-4db1-96df-972a054088a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
