<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Skip</name>
   <tag></tag>
   <elementGuidId>579fd5f9-541e-4eeb-987b-cf638c8d7694</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#skip_holder > label.col-sm-4.control-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='skip_holder']/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>da8a0f1c-6efb-44b2-b147-77303e89f838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ffInput_skip</value>
      <webElementGuid>8e9f37ef-a903-4e58-9ade-955c31825dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-sm-4 control-label</value>
      <webElementGuid>54895a47-ec7b-4b38-9ffd-f9c1aa789597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Skip</value>
      <webElementGuid>03df65da-d61a-4686-9a54-efa04c08e9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skip_holder&quot;)/label[@class=&quot;col-sm-4 control-label&quot;]</value>
      <webElementGuid>86c5af5d-ae03-4a9f-8510-dca1586417cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='skip_holder']/label</value>
      <webElementGuid>87c8b763-6b15-49d2-821a-c94a0c7de8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/label</value>
      <webElementGuid>4b3d06eb-7da2-4c75-846b-4331115f6592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Skip' or . = 'Skip')]</value>
      <webElementGuid>430bccce-e392-462f-84ca-1676943dc84c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
