<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_The amount must be less than or equal 100001709</name>
   <tag></tag>
   <elementGuidId>38c436ac-65ca-4f1d-8446-a8441e938bdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#amount_holder > div.col-sm-8 > p.text-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='amount_holder']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b19016ff-e795-47e2-8083-33e223a7f60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>3c2bdec8-a5f5-472d-bbe0-7f891c1da46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The amount must be less than or equal 100001709.</value>
      <webElementGuid>3bd97a36-fa6d-4a75-9c14-6a37399f5f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amount_holder&quot;)/div[@class=&quot;col-sm-8&quot;]/p[@class=&quot;text-danger&quot;]</value>
      <webElementGuid>33cd897a-4fe9-4a92-a7bc-d2c04cdb28d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='amount_holder']/div/p</value>
      <webElementGuid>27970889-a093-42be-a7b3-e3a4db92325d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[4]/div/p</value>
      <webElementGuid>5144aaab-0f09-4041-91b1-45ffe320570e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'The amount must be less than or equal 100001709.' or . = 'The amount must be less than or equal 100001709.')]</value>
      <webElementGuid>e32ab020-336f-492d-9a4b-935391420aa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
