<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_The repeat until must be a date after 2024-01-08</name>
   <tag></tag>
   <elementGuidId>2388e4d6-5741-4906-95b6-9137c65a0a20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.text-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='repeat_until_holder']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>c79b4672-b398-4fb0-aa99-7c0a38ca5482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>1fe91aa9-3d9d-4ee5-9c44-6b780e0ece7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The repeat until must be a date after 2024-01-08.</value>
      <webElementGuid>8ee91ab0-c05f-4d36-b43a-755b0f114855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repeat_until_holder&quot;)/div[@class=&quot;col-sm-8&quot;]/p[@class=&quot;text-danger&quot;]</value>
      <webElementGuid>b72d15cc-1433-4221-a904-9fc378bfbc75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repeat_until_holder']/div/p</value>
      <webElementGuid>c6399a52-d5be-4e2b-8948-bcdce38486a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/p</value>
      <webElementGuid>aae912df-b107-44ef-a6ab-8194e0f74c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'The repeat until must be a date after 2024-01-08.' or . = 'The repeat until must be a date after 2024-01-08.')]</value>
      <webElementGuid>02ee0e33-159a-427f-ae74-1bbfa53d374c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
