<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(no currency)Euro ()Hungarian forint_3ba76d</name>
   <tag></tag>
   <elementGuidId>66681345-b811-4107-b653-c7d7f9eb6846</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_foreign_currency_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_foreign_currency_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ab0a46fa-be54-4d38-82e0-7c18022768c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>ec53f18e-1e80-4ff8-acc9-34f0b92740cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>foreign_currency_id</value>
      <webElementGuid>77490102-ff43-48ed-9505-e0ce21756b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_foreign_currency_id</value>
      <webElementGuid>59160863-0575-4979-b566-e10a3dc62106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>14fa5ebf-6cb2-4ba8-bc79-3a52f151a636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>06e9d67c-4c03-4d2a-a088-ec9357530b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(no currency)Euro (€)Hungarian forint (Ft)Ukrainian hryvnia (₴)US Dollar ($)</value>
      <webElementGuid>1869f42c-d8b9-47bb-824a-1a7029a0a3e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_foreign_currency_id&quot;)</value>
      <webElementGuid>fb6ad6bb-e55e-48f6-9eda-31da4ae0b2c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_foreign_currency_id']</value>
      <webElementGuid>56e00e81-97eb-4166-bc41-4af867120e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='foreign_currency_id_holder']/div/select</value>
      <webElementGuid>7a858de7-228a-42e4-bb91-9448317b4f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/select</value>
      <webElementGuid>75ea7758-712e-42c9-a7b7-adf3030fa334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'foreign_currency_id' and @id = 'ffInput_foreign_currency_id' and (text() = '(no currency)Euro (€)Hungarian forint (Ft)Ukrainian hryvnia (₴)US Dollar ($)' or . = '(no currency)Euro (€)Hungarian forint (Ft)Ukrainian hryvnia (₴)US Dollar ($)')]</value>
      <webElementGuid>10609895-40f7-49c2-8313-d6a64710f9d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
