<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AdobeAlibabaamazon.comBaker BobBuy a_270406</name>
   <tag></tag>
   <elementGuidId>28027b32-a6cb-41c7-a653-36d6c58a1d86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_withdrawal_destination_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_withdrawal_destination_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d47bbd92-ad4b-463e-8515-a7bd084c6a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>320d3bf8-ff88-4952-b647-d1feb5aa130f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>withdrawal_destination_id</value>
      <webElementGuid>d4eba436-d9dd-4456-8325-50bd35685a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_withdrawal_destination_id</value>
      <webElementGuid>a05fb54a-4df8-44ce-8316-749035e24d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>19ead32b-7b40-4bb3-a576-2d7153f8f5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>45a012ec-adad-4f2d-96a6-1ec4dccb4ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AdobeAlibabaamazon.comBaker BobBuy and LargeCafe CentralDrugstoreGoogle ExpenseGreenchoice ElectricityHalfords Car PartsHealth Plus InsureriCentre Mac StoreJumper Pet Food StoreKwik-E-MartLand lordMcDonaldsShellSome online storeStarbucksStudent Loan OrganizationSuperMarketTaxes and Revenues Government serviceThe Water CompanyXS4All ISPDUO Student loansAMEX Credit Card debtDebtffaaf(cash)</value>
      <webElementGuid>6c58b293-5907-43eb-b24b-d7795181909c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_withdrawal_destination_id&quot;)</value>
      <webElementGuid>6371a116-b809-4465-8855-c4ec514ebbb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_withdrawal_destination_id']</value>
      <webElementGuid>41bd3e31-39d5-40a9-8e7a-bb9480af757e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='withdrawal_destination_id_holder']/div/select</value>
      <webElementGuid>cc597981-fdfd-4d64-83e0-8693311ee429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/select</value>
      <webElementGuid>766d928d-6d7e-4c70-9606-b974ee9b894e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'withdrawal_destination_id' and @id = 'ffInput_withdrawal_destination_id' and (text() = 'AdobeAlibabaamazon.comBaker BobBuy and LargeCafe CentralDrugstoreGoogle ExpenseGreenchoice ElectricityHalfords Car PartsHealth Plus InsureriCentre Mac StoreJumper Pet Food StoreKwik-E-MartLand lordMcDonaldsShellSome online storeStarbucksStudent Loan OrganizationSuperMarketTaxes and Revenues Government serviceThe Water CompanyXS4All ISPDUO Student loansAMEX Credit Card debtDebtffaaf(cash)' or . = 'AdobeAlibabaamazon.comBaker BobBuy and LargeCafe CentralDrugstoreGoogle ExpenseGreenchoice ElectricityHalfords Car PartsHealth Plus InsureriCentre Mac StoreJumper Pet Food StoreKwik-E-MartLand lordMcDonaldsShellSome online storeStarbucksStudent Loan OrganizationSuperMarketTaxes and Revenues Government serviceThe Water CompanyXS4All ISPDUO Student loansAMEX Credit Card debtDebtffaaf(cash)')]</value>
      <webElementGuid>881b698c-d99b-41b8-b7b9-fcaf7c2161b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
