<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(no currency)Swiss franc (CHF)Euro (_0331dc</name>
   <tag></tag>
   <elementGuidId>13ec24d3-1098-4d8d-86dc-54f2987d7133</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_foreign_currency_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_foreign_currency_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5751f23f-a8b4-43d0-8945-3a5d79ccad8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>aae79933-df8f-4647-aafc-d66a6c4a1caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>foreign_currency_id</value>
      <webElementGuid>6f0569d0-2ffc-471a-8641-6cbc8f18bc17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_foreign_currency_id</value>
      <webElementGuid>acdf45e1-cf8f-440a-91d8-03e2bde2c0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6988f274-6073-4cd2-90ad-e6256cf71911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4707f060-a388-4235-874b-8f9417d33319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(no currency)Swiss franc (CHF)Euro (€)US Dollar ($)</value>
      <webElementGuid>4ed6d3d4-140a-42e7-b16c-d2d31d81c69d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_foreign_currency_id&quot;)</value>
      <webElementGuid>5f8e9c8d-c434-4931-af09-e2b1d32f721c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_foreign_currency_id']</value>
      <webElementGuid>215560e8-40e1-4983-8661-655ede39112d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='foreign_currency_id_holder']/div/select</value>
      <webElementGuid>563ff717-0423-4f73-969c-127393b26c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/select</value>
      <webElementGuid>a8caf6c1-e1fb-4b60-b789-14ce742e6a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'foreign_currency_id' and @id = 'ffInput_foreign_currency_id' and (text() = '(no currency)Swiss franc (CHF)Euro (€)US Dollar ($)' or . = '(no currency)Swiss franc (CHF)Euro (€)US Dollar ($)')]</value>
      <webElementGuid>149a55f0-2cfe-4bac-ad3b-21bc43f040ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
