<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Just create the transactionSkip the _f92ce5</name>
   <tag></tag>
   <elementGuidId>3314990d-9026-42ec-bca5-c1f6941b21e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_weekend</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_weekend']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ffbf66d4-0af6-420f-a93f-3aa6b4d2b98c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>67d5d2ea-aafc-4a33-9caa-14ecfabc2515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>weekend</value>
      <webElementGuid>7895d29b-f701-4015-9d07-58ad4b738a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_weekend</value>
      <webElementGuid>9dbe25b3-151e-4b55-8e50-f145aefe80f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8958699a-0f42-4363-8a76-a7c44b10dfa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bd0aa30d-e8d4-40bd-aff2-766620b4de6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Just create the transactionSkip the occurrenceCreate the transaction on the previous Friday insteadCreate the transaction on the next Monday instead</value>
      <webElementGuid>7c72e0ea-f30f-4300-95d6-022700901acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_weekend&quot;)</value>
      <webElementGuid>31eebd33-5e6f-435c-b380-1979b681637f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_weekend']</value>
      <webElementGuid>f0bc2207-d8b2-4485-ae1b-859890f97cdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='weekend_holder']/div/select</value>
      <webElementGuid>7b0d202d-fca7-4e04-b916-b6c86e05534d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>f5099c08-3971-43fe-8602-ca49cb5b13ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'weekend' and @id = 'ffInput_weekend' and (text() = 'Just create the transactionSkip the occurrenceCreate the transaction on the previous Friday insteadCreate the transaction on the next Monday instead' or . = 'Just create the transactionSkip the occurrenceCreate the transaction on the previous Friday insteadCreate the transaction on the next Monday instead')]</value>
      <webElementGuid>6e635306-fb63-4b56-a0b3-3a77a1edd425</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
