<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Repeat foreverRepeat until dateRepea_4f389d</name>
   <tag></tag>
   <elementGuidId>85d521dd-280e-4352-a62c-e48479dcb10f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_repetition_end</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_repetition_end']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d750e1e8-50bc-4e2d-8b2c-51aeb2b566c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>d7086c77-3c43-4124-a9a3-0ec59b02fe1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>repetition_end</value>
      <webElementGuid>7bb20355-f0e8-49cb-a930-d123c9765c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_repetition_end</value>
      <webElementGuid>fd4ded24-223b-4e7d-b84c-3be0eaf3125a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6c57fabf-330c-4338-aee5-e0ecc5bfbd46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ef457bab-e0f3-452a-860e-812b2d37ec2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Repeat foreverRepeat until dateRepeat a number of times</value>
      <webElementGuid>4e26b69c-15a6-4b61-9b47-27d54d674643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_repetition_end&quot;)</value>
      <webElementGuid>a7825b37-3675-46b1-ae9e-56bc2a2bf828</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_repetition_end']</value>
      <webElementGuid>94467c74-f9ab-4bdd-9e73-26c2ae2b91a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repetition_end_holder']/div/select</value>
      <webElementGuid>e247eed3-d03f-4b41-a2af-ca4d8f2013d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/select</value>
      <webElementGuid>92b1d718-d0be-4245-878c-e65c0f16da04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'repetition_end' and @id = 'ffInput_repetition_end' and (text() = 'Repeat foreverRepeat until dateRepeat a number of times' or . = 'Repeat foreverRepeat until dateRepeat a number of times')]</value>
      <webElementGuid>7b1a140b-78bc-4a6d-9a3c-10026c1ccfb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
