<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Cash walletChecking AccountChecking _ec45d6</name>
   <tag></tag>
   <elementGuidId>164f3bee-7e6c-424b-a35d-d93feeee8c11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_source_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_source_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>659401bc-9ccf-43f7-8282-035261af3883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>41887dae-c038-42a9-a4f3-2fa90fd97992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>source_id</value>
      <webElementGuid>de59e676-1599-47d6-934b-6460d0e2556b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_source_id</value>
      <webElementGuid>993d082b-edb1-4869-a2cc-2f8e55069bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fb05fc78-b273-4887-9af0-622d6cae1d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fe27bcfc-0002-4771-90ea-143262b75a1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cash walletChecking AccountChecking account in GBPacccCredit card in USDSavings AccountShared Checking AccountDUO Student loansAMEX Credit Card debtDebtffaaf</value>
      <webElementGuid>88f3eff0-90b7-4b8d-ab28-ef29b5fc4661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_source_id&quot;)</value>
      <webElementGuid>de4257b7-613c-48df-98b5-17b6281de1fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_source_id']</value>
      <webElementGuid>002aba38-0ab2-4a65-9c54-267b422fd6ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='source_id_holder']/div/select</value>
      <webElementGuid>adb687eb-09a3-4791-b77c-851ecdb80fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[5]/div/select</value>
      <webElementGuid>f81dbaaf-88d3-4bd7-bad1-9a853b6ad103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'source_id' and @id = 'ffInput_source_id' and (text() = 'Cash walletChecking AccountChecking account in GBPacccCredit card in USDSavings AccountShared Checking AccountDUO Student loansAMEX Credit Card debtDebtffaaf' or . = 'Cash walletChecking AccountChecking account in GBPacccCredit card in USDSavings AccountShared Checking AccountDUO Student loansAMEX Credit Card debtDebtffaaf')]</value>
      <webElementGuid>cbde45b4-e2c5-4e85-ae84-3b1df52174a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_destination_id']</value>
      <webElementGuid>c0a71cf3-e70e-4353-b6b0-7807289cdecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='destination_id_holder']/div/select</value>
      <webElementGuid>448498c4-69dd-4e1a-bc0c-9ef32265ee0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/select</value>
      <webElementGuid>1334cbc1-cc3f-45d3-9427-11dd40b1739b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'destination_id' and @id = 'ffInput_destination_id' and (text() = 'Cash walletChecking AccountChecking account in GBPacccCredit card in USDSavings AccountShared Checking AccountDUO Student loansAMEX Credit Card debtDebtffaaf' or . = 'Cash walletChecking AccountChecking account in GBPacccCredit card in USDSavings AccountShared Checking AccountDUO Student loansAMEX Credit Card debtDebtffaaf')]</value>
      <webElementGuid>1868cabf-785a-47e1-aa78-7b5522443bf5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
