<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(no currency)Euro ()Hungarian forint_850ea1</name>
   <tag></tag>
   <elementGuidId>8d0d0214-8008-4084-bacf-1fc3e6cd73d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_foreign_currency_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_foreign_currency_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1af5af66-9c2d-4a2d-96bb-1f0c6c61ae7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>910b033c-aff3-4e1f-9310-016ebf3a3b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>foreign_currency_id</value>
      <webElementGuid>26d8ff55-06d8-4caf-a1a4-f2f3a716ecca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_foreign_currency_id</value>
      <webElementGuid>dceb3c6e-9026-49d1-b463-92283e2fd793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f0dc502a-ae8f-42e6-bafb-5e6c41faa960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>41c26936-82ff-46fb-93a2-6da8a35d6880</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(no currency)Euro (€)Hungarian forint (Ft)Ukrainian hryvnia (₴)</value>
      <webElementGuid>2dce948f-4b08-4b23-860f-e27a2935e00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_foreign_currency_id&quot;)</value>
      <webElementGuid>d3adace3-c425-44c5-aea5-1ba49aa3f094</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_foreign_currency_id']</value>
      <webElementGuid>3f19df16-2644-4844-bbe9-6b85607cc715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='foreign_currency_id_holder']/div/select</value>
      <webElementGuid>40dc3e9c-127d-45c6-abf0-f0a50bf2514e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/select</value>
      <webElementGuid>0741d78a-9e2a-4032-890f-b00efad9ec74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'foreign_currency_id' and @id = 'ffInput_foreign_currency_id' and (text() = '(no currency)Euro (€)Hungarian forint (Ft)Ukrainian hryvnia (₴)' or . = '(no currency)Euro (€)Hungarian forint (Ft)Ukrainian hryvnia (₴)')]</value>
      <webElementGuid>3d46ca78-950f-4963-b3ff-f41ffcd15ec2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
